In [9]:
import pyterrier as pt
from pathlib import Path
from ir_measures import Recall, nDCG, RR

def load_run(directory):
    return pt.transformer.get_transformer(pt.io.read_results(Path(directory) / "run.txt.gz"))

In [14]:
def experiment(dataset_split):
    topics = pt.datasets.get_dataset(f"irds:trec-tot/2025/{dataset_split}").get_topics()
    qrels = pt.datasets.get_dataset(f"irds:trec-tot/2025/{dataset_split}").get_qrels()
    bm25_anserini = load_run(f'../anserini-bm25-retrieval/runs/{dataset_split}-oracle/')
    bm25_pyterrier = load_run(f'../pyterrier-bm25-retrieval/runs/bm25-oracle/{dataset_split}/')
    bert_dense = load_run(f'../lightning-dense-retrieval/runs/{dataset_split}-oracle')

    runs = [
        bm25_anserini,
        bm25_pyterrier,
        bert_dense
    ]
    run_names = [
        "BM25 (Anserini)", "BM25 (PyTerrier)", "Dense Retrieval"
    ]
    return pt.Experiment(runs, names=run_names, topics=topics, qrels=qrels, eval_metrics=[nDCG@10, nDCG@1000, Recall@1000])

In [15]:
experiment("train")

               name   nDCG@10  nDCG@1000    R@1000
0   BM25 (Anserini)  0.993007   0.993007  0.993007
1  BM25 (PyTerrier)  1.000000   1.000000  1.000000
2   Dense Retrieval  0.056534   0.101909  0.384615

In [16]:
experiment("dev1")

               name   nDCG@10  nDCG@1000    R@1000
0   BM25 (Anserini)  0.992958   0.992958  0.992958
1  BM25 (PyTerrier)  1.000000   1.000000  1.000000
2   Dense Retrieval  0.122350   0.161775  0.408451

In [20]:
experiment("dev2")

,name,nDCG@10,nDCG@1000,RR@1000,R@10,R@1000,R@10000
0,BM25 (Anserini),1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
1,BM25 (PyTerrier),1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
2,Dense Retrieval (lightning-ir),0.074855,0.106228,0.065415,0.118881,0.321678,0.321678

In [17]:
experiment("dev3")

               name   nDCG@10  nDCG@1000    R@1000
0   BM25 (Anserini)  1.000000   1.000000  1.000000
1  BM25 (PyTerrier)  1.000000   1.000000  1.000000
2   Dense Retrieval  0.145715   0.205859  0.617537